last
VitmiTor/firstTypeScript pull request #1
Opened 2023-08-19 15:40 UTC by VitmiTor

2023-08-19 16:08 UTC, calvarioTeacher31 commented on src/ejercicios/tarea1/ejercicio12.ts
> +
espacios muertos

2023-08-19 16:09 UTC, calvarioTeacher31 commented on src/ejercicios/tarea1/ejercicio3.ts
> +
espacio muerto

2023-08-19 16:09 UTC, calvarioTeacher31 commented on src/ejercicios/tarea1/ejercicio5.ts
> +
espacio muerto

2023-08-19 16:09 UTC, calvarioTeacher31 commented on src/ejercicios/tarea1/ejercicio6.ts
> +
espacio muerto

2023-08-19 16:09 UTC, calvarioTeacher31 commented on src/ejercicios/tarea1/ejercicio9.ts
> +
espacio muerto

2023-08-19 16:09 UTC, calvarioTeacher31 commented on src/ejercicios/tarea2/ejercicico10.ts
> +    residuo = aux % 10;
const residuo = aux % 10; borra la línea 7

2023-08-19 16:10 UTC, calvarioTeacher31 commented on src/ejercicios/tarea2/ejercicico10.ts
> +  }
return numero === inversa

2023-08-19 16:10 UTC, calvarioTeacher31 commented on src/ejercicios/tarea2/ejercicico9.ts
> +
espacio muerto

2023-08-19 16:10 UTC, calvarioTeacher31 commented on src/ejercicios/tarea2/ejercicio4.ts
> +
espacio muerto

2023-08-19 16:10 UTC, calvarioTeacher31 commented on src/ejercicios/tarea2/ejercicio5.ts
> +
espacio muerto

2023-08-19 16:10 UTC, calvarioTeacher31 commented on src/ejercicios/tarea2/ejercicio7.ts
> +
espacio muerto

2023-08-19 16:10 UTC, calvarioTeacher31 commented on src/ejercicios/tarea3/ejercicio10.ts
> +const arrayMenor = [];
const arrayMayor: number[] = []
const arrayMenor: number[] = []

2023-08-19 16:11 UTC, calvarioTeacher31 commented on src/ejercicios/tarea3/ejercicio6.ts
> +imprimirMensaje(cantidadN, resultado);
deja un espacio entre esto

2023-08-19 16:11 UTC, calvarioTeacher31 commented on src/ejercicios/tarea3/ejercicio8.ts
> +const arrayCompuestos = [];
```
const arrayMayor: number[] = []
const arrayMenor: number[] = []
```

2023-08-19 16:12 UTC, calvarioTeacher31 commented on src/ejercicios/tarea3/ejercicio9.ts
> +const arrayNotCapicua = [];
`const arrayCapicua : number[] = []
const arrayNotCapicua : number[] = []`

2023-08-19 16:12 UTC, calvarioTeacher31 commented on src/ejercicios/tarea4/ejercicio1.ts
> +
espacios muertos

2023-08-19 16:13 UTC, calvarioTeacher31 commented on src/ejercicios/tarea4/ejercicio12.ts
> +const arrayNoCapicuas = [];
```
const arrayCapicuas : number[] = []
const arrayNotCapicuas : number[] = []
```

2023-08-19 16:13 UTC, calvarioTeacher31 commented on src/ejercicios/tarea4/ejercicio5.ts
> +const arrayCulpables = [];
```
const arrayInocentes : string[] = []
const arrayCulpables : string[] = []
```

2023-08-19 16:14 UTC, calvarioTeacher31 commented on src/ejercicios/tarea4/ejercicio9.ts
> +const arrayPeso = [];
```
const arrayX: number[] = []
const arrayPeso: number[] = []
```

2023-08-19 16:14 UTC, calvarioTeacher31 commented on src/utilities/randomUtilities.ts
> +export const generarDecimalAleatorio = (min, max) => {
falta tipo retorno

2023-08-19 16:14 UTC, calvarioTeacher31 commented on src/utilities/arrayUtiliites.ts
> +  const array = [];
```
const array: number[] = []
```

2023-08-19 16:14 UTC, calvarioTeacher31 commented on src/utilities/arrayUtiliites.ts
> +"use strict";
quita use strict

2023-08-19 16:15 UTC, calvarioTeacher31 commented on src/utilities/algorithmsUtilities.ts
> +    residuo = aux % 10;
`const residuo = aux % 10; //borra la línea 15`

2023-08-19 16:17 UTC, calvarioTeacher31 commented on src/utilities/arrayUtiliites.ts
> +export const arrayAleatorio = (n, min, max) => {
falta tipo retorno

2023-08-19 16:17 UTC, calvarioTeacher31 commented on src/utilities/arrayUtiliites.ts
> +export const arrayAleatorio = (n, min, max) => {
falta tipo parametros

2023-08-19 16:17 UTC, calvarioTeacher31 requested changes
revisar comentarios

2023-08-19 22:05 UTC, VitmiTor commented on src/ejercicios/tarea1/ejercicio12.ts
> +
resuelto

2023-08-19 22:05 UTC, VitmiTor commented on src/ejercicios/tarea1/ejercicio3.ts
> +
resuelto

2023-08-19 22:06 UTC, VitmiTor commented on src/ejercicios/tarea1/ejercicio5.ts
> +
resuelto

2023-08-19 22:06 UTC, VitmiTor commented on src/ejercicios/tarea1/ejercicio6.ts
> +
resuelto

2023-08-19 22:06 UTC, VitmiTor commented on src/ejercicios/tarea1/ejercicio9.ts
> +
resuelto

2023-08-19 22:07 UTC, VitmiTor commented on src/ejercicios/tarea2/ejercicico10.ts
> +  }
resuelto

2023-08-19 22:07 UTC, VitmiTor commented on src/ejercicios/tarea2/ejercicico10.ts
> +    residuo = aux % 10;
resuelto

2023-08-19 22:08 UTC, VitmiTor commented on src/ejercicios/tarea2/ejercicico9.ts
> +
resuelto

2023-08-19 22:08 UTC, VitmiTor commented on src/ejercicios/tarea2/ejercicio4.ts
> +
resuelto

2023-08-19 22:08 UTC, VitmiTor commented on src/ejercicios/tarea2/ejercicio5.ts
> +
resuelto

2023-08-19 22:09 UTC, VitmiTor commented on src/ejercicios/tarea2/ejercicio7.ts
> +
resuelto

2023-08-19 22:10 UTC, VitmiTor commented on src/ejercicios/tarea3/ejercicio10.ts
> +const arrayMenor = [];
resuelto

2023-08-19 22:10 UTC, VitmiTor commented on src/ejercicios/tarea3/ejercicio6.ts
> +imprimirMensaje(cantidadN, resultado);
resuelto

2023-08-19 22:11 UTC, VitmiTor commented on src/ejercicios/tarea3/ejercicio8.ts
> +const arrayCompuestos = [];
resuelto

2023-08-19 22:11 UTC, VitmiTor commented on src/ejercicios/tarea3/ejercicio9.ts
> +const arrayNotCapicua = [];
resuelto

2023-08-19 22:12 UTC, VitmiTor commented on src/ejercicios/tarea4/ejercicio1.ts
> +
resuelto

2023-08-19 22:12 UTC, VitmiTor commented on src/ejercicios/tarea4/ejercicio12.ts
> +const arrayNoCapicuas = [];
resuelto

2023-08-19 22:13 UTC, VitmiTor commented on src/ejercicios/tarea4/ejercicio5.ts
> +const arrayCulpables = [];
resuelto

2023-08-19 22:13 UTC, VitmiTor commented on src/ejercicios/tarea4/ejercicio9.ts
> +const arrayPeso = [];
resuelto

2023-08-19 22:14 UTC, VitmiTor commented on src/utilities/randomUtilities.ts
> +export const generarDecimalAleatorio = (min, max) => {
resuelto

2023-08-19 22:15 UTC, VitmiTor commented on src/utilities/arrayUtiliites.ts
> +  const array = [];
resuelto

2023-08-19 22:15 UTC, VitmiTor commented on src/utilities/arrayUtiliites.ts
> +"use strict";
resuelto

2023-08-19 22:16 UTC, VitmiTor commented on src/utilities/algorithmsUtilities.ts
> +    residuo = aux % 10;
resuelto

2023-08-19 22:17 UTC, VitmiTor commented on src/utilities/arrayUtiliites.ts
> +export const arrayAleatorio = (n, min, max) => {
resuelto

2023-08-20 03:12 UTC, calvarioTeacher31 approved these changes

2023-08-20 03:12 UTC, merged